_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
  WEIGHTS: "/content/drive/allam/last_checkpoint.pth"
  VIT:
    NAME: "dit_base_patch16"
SOLVER:
  WARMUP_ITERS: 1000
  IMS_PER_BATCH: 5
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 3000
OUTPUT_DIR: $AMLT_OUTPUT_DIR
